html_elements_data: list[dict] = [
    # calculation XML
    {
        "Type": "90F",
        "Element": "us-gaap--Land",
        "Unit": "Canadian Dollar",
        "PreElementParent": "us-gaap:AssetsAbstract",
        "Indenting": "1",
        "Precision": "3",
        "CountedAs": "6",
        "CalculationParent": "us-gaap--BuildingsAndImprovementsGross",
        "Period": "20240223",
        "Axis_Member": "us-gaap--StatementClassOfStockAxis__us-gaap--ClassOfStockDomain__msft--CommonStock025ParValueMember",
        "PreferredLabel": "Land",
        "PreferredLabelType": "terselabel",
        "Table": "us-gaap--StatementTable",
        "LineItem": "us-gaap--StatementLineItems",
        "RootLevelAbstract": "us-gaap--LandAndLandImprovementsAbstract",
        "RoleName": "StatementConsoildatedBalanceSheet",
        "UniqueId": "0efb6deb824c493da1b6e03669691c37",
    },
    {
        "Type": "90F",
        "Element": "us-gaap--Buliding",
        "Unit": "Canadian Dollar",
        "PreElementParent": "us-gaap:AssetsAbstract",
        "Indenting": "1",
        "Precision": "3",
        "CountedAs": "6",
        "CalculationParent": "us-gaap--BuildingsAndImprovementsGross",
        "Period": "20240223",
        "Axis_Member": "us-gaap--StatementClassOfStockAxis__us-gaap--ClassOfStockDomain__msft--CommonStock025ParValueMember",
        "PreferredLabel": "Land",
        "PreferredLabelType": "terselabel",
        "Table": "us-gaap--StatementTable",
        "LineItem": "us-gaap--StatementLineItems",
        "RootLevelAbstract": "us-gaap--LandAndLandImprovementsAbstract",
        "RoleName": "StatementConsoildatedBalanceSheet",
        "UniqueId": "0efb6deb824c493da1b6e03669691c37",
    },
    {
        "Type": "90F",
        "Element": "us-gaap--BuildingsAndImprovementsGross",
        "Unit": "Canadian Dollar",
        "PreElementParent": "us-gaap:AssetsAbstract",
        "Indenting": "1",
        "Precision": "3",
        "CountedAs": "6",
        "CalculationParent": "us-gaap--AssetsNoncurrent",
        "Period": "20240223",
        "Axis_Member": "us-gaap--StatementClassOfStockAxis__us-gaap--ClassOfStockDomain__msft--CommonStock025ParValueMember",
        "PreferredLabel": "Land",
        "PreferredLabelType": "terselabel",
        "Table": "us-gaap--StatementTable",
        "LineItem": "us-gaap--StatementLineItems",
        "RootLevelAbstract": "us-gaap--LandAndLandImprovementsAbstract",
        "RoleName": "StatementConsoildatedBalanceSheet",
        "UniqueId": "0efb6deb824c493da1b6e03669691c37",
    },
    {
        "Type": "90F",
        "Element": "us-gaap--AssetsNoncurrent",
        "Unit": "Canadian Dollar",
        "PreElementParent": "us-gaap:AssetsAbstract",
        "Indenting": "1",
        "Precision": "3",
        "CountedAs": "6",
        "CalculationParent": "us-gaap--Assests",
        "Period": "20240223",
        "Axis_Member": "us-gaap--StatementClassOfStockAxis__us-gaap--ClassOfStockDomain__msft--CommonStock025ParValueMember",
        "PreferredLabel": "Land",
        "PreferredLabelType": "terselabel",
        "Table": "us-gaap--StatementTable",
        "LineItem": "us-gaap--StatementLineItems",
        "RootLevelAbstract": "us-gaap--LandAndLandImprovementsAbstract",
        "RoleName": "StatementConsoildatedBalanceSheet",
        "UniqueId": "0efb6deb824c493da1b6e03669691c37",
    },
    # earlier
    # {
    #     "Type": "90F",
    #     "Element": "us-gaap--Land",
    #     "Unit": "Canadian Dollar",
    #     "PreElementParent": "us-gaap:AssetsAbstract",
    #     "Indenting": "1",
    #     "Precision": "",
    #     "CountedAs": "",
    #     "Calculation": "",
    #     "Period": "",
    #     "Axis_Member": "us-gaap--StatementClassOfStockAxis_us-gaap--ClassOfStockDomain_msft--CommonStock025ParValueMember",
    #     "PreferredLabel": "Land",
    #     "PreferredLabelType": "terselabel",
    #     "Table": "us-gaap--StatementTable",
    #     "LineItem": "us-gaap_StatementLineItems",
    #     "RootLevelAbstract": "us-gaap--StatementOfFinancialPositionAbstract",
    #     "RoleName": "StatementConsoildatedBalanceSheet",
    #     "UniqueId": "0efb6deb824c493da1b6e03669691c37",
    # },
    # {
    #     "Type": "90F",
    #     "Element": "us-gaap--NetIncomeLoss",
    #     "Unit": "Canadian Dollar",
    #     "PreElementParent": "us-gaap:EarningsPerShareAbstract",
    #     "Indenting": "1",
    #     "Precision": "",
    #     "CountedAs": "",
    #     "Calculation": "",
    #     "Period": "",
    #     "Axis_Member": "srt--ProductOrServiceAxis_srt--ProductsAndServicesDomain_msft--IPhoneMember__us-gaap--RevenueRemainingPerformanceObligationExpectedTimingOfSatisfactionStartDateAxis_msft--RevenueRemainingPerformanceObligationExpectedTimingOfSatisfactionStartDateDomain_us-gaap--CommercialPaperMember",
    #     "PreferredLabel": "Net Income",
    #     "PreferredLabelType": "terselabel",
    #     "Table": "us-gaap--DisaggregationOfRevenueTable",
    #     "LineItem": "us-gaap--DisaggregationOfRevenueLineItems",
    #     "RootLevelAbstract": "us-gaap--IncomeStatementAbstract",
    #     "RoleName": "CondensedConsolidatedStatementsOfOperationsUnaudited",
    #     "UniqueId": "0efb6deb824c493da1b6e03669691c59",
    # },
]
