labels_dict = {
    "Standard Label": "http://www.xbrl.org/2003/role/label",
    "Positive Label": "http://www.xbrl.org/2003/role/positiveLabel",
    "Positive Terse Label": "http://www.xbrl.org/2003/role/positiveTerseLabel",
    "Positive Verbose Label": "http://www.xbrl.org/2003/role/positiveVerboseLabel",
    "Negative Label": "http://www.xbrl.org/2003/role/negativeLabel",
    "Negative Terse Label": "http://www.xbrl.org/2003/role/negativeTerseLabel",
    "Negative Verbose Label": "http://www.xbrl.org/2003/role/negativeVerboseLabel",
    "Zero Label": "http://www.xbrl.org/2003/role/zeroLabel",
    "Zero Terse Label": "http://www.xbrl.org/2003/role/zeroTerseLabel",
    "Zero Verbose Label": "http://www.xbrl.org/2003/role/zeroVerboseLabel",
    "Total Label": "http://www.xbrl.org/2003/role/totalLabel",
    "Negated Label": "http://www.xbrl.org/2009/role/negatedLabel",
    "Negated Period End Label": "http://www.xbrl.org/2009/role/negatedPeriodEndLabel",
    "Negated Period Start Label": "http://www.xbrl.org/2009/role/negatedPeriodStartLabel",
    "Negated Total Label": "http://www.xbrl.org/2009/role/negatedTotalLabel",
    "Negated Net Label": "http://www.xbrl.org/2009/role/negatedNetLabel",
    "Negated Terse Label": "http://www.xbrl.org/2009/role/negatedTerseLabel",
    "Negated": "http://xbrl.us/us-gaap/role/label/negated",
    "Negated Total": "http://xbrl.us/us-gaap/role/label/negatedTotal",
    "Negated Period Start": "http://xbrl.us/us-gaap/role/label/negatedPeriodStart",
    "Negated Period End": "http://xbrl.us/us-gaap/role/label/negatedPeriodEnd",
    "Terse": "https://www.xbrl.org/2003/role/terseLabel",
    "Verbose": "http://www.xbrl.org/2003/role/verboseLabel",
}
